//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaChamadosFiap.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaChamadosFiapEntities : DbContext
    {
        public SistemaChamadosFiapEntities()
            : base("name=SistemaChamadosFiapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAtendente> tbAtendentes { get; set; }
        public virtual DbSet<tbChamado> tbChamadoes { get; set; }
        public virtual DbSet<tbChamadoInteracao> tbChamadoInteracaos { get; set; }
        public virtual DbSet<tbCliente> tbClientes { get; set; }
    }
}
