//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaChamadosFiap.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbChamadoInteracao
    {
        public int Id { get; set; }
        public string Mensagem { get; set; }
        public int IdChamado { get; set; }
        public System.DateTime DtInteracao { get; set; }
        public string Usuario { get; set; }
    
        public virtual tbChamado tbChamado { get; set; }
    }
}
